-- -- METHOD 1
-- WITH JOINED_RESULT AS (
--     SELECT 
--         P.SALES_ID,
--         P.NAME,
--         C.NAME AS companyName
--     FROM SALESPERSON P
--     LEFT JOIN ORDERS O ON P.SALES_ID = O.SALES_ID
--     LEFT JOIN COMPANY C ON C.COM_ID = O.COM_ID
-- )
-- SELECT NAME
-- FROM JOINED_RESULT
-- GROUP BY NAME
-- HAVING SUM(IF(companyName = 'RED',1,0)) = 0;

-- METHOD 2
SELECT NAME
FROM SALESPERSON
WHERE SALES_ID NOT IN(
    SELECT SALES_ID FROM ORDERS
    WHERE COM_ID = (
        SELECT COM_ID FROM COMPANY WHERE NAME="RED"
    )
)