select 
  U.USER_ID AS BUYER_ID,
  U.JOIN_DATE,
  COUNT(O.ORDER_ID) AS ORDERS_IN_2019
FROM USERS U
LEFT JOIN ORDERS O
  ON U.USER_ID = O.BUYER_ID 
  AND O.ORDER_DATE BETWEEN '2019-01-01' AND '2019-12-31'
GROUP BY U.USER_ID
