WITH COUNT_OF_CANCEL AS (
    SELECT 
        T.REQUEST_AT AS DAY,
        COUNT(*) AS CANCELLED
    FROM TRIPS T
    JOIN USERS U1 ON T.CLIENT_ID = U1.USERS_ID
    JOIN USERS U2 ON T.DRIVER_ID = U2.USERS_ID
    WHERE T.STATUS LIKE 'cancelled_by_%'
      AND U1.BANNED = 'No'
      AND U2.BANNED = 'No'
      AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
    GROUP BY T.REQUEST_AT
),
COUNT_OF_TOTAL AS (
    SELECT 
        T.REQUEST_AT AS DAY,
        COUNT(*) AS TOTAL_TRIPS
    FROM TRIPS T
    JOIN USERS U1 ON T.CLIENT_ID = U1.USERS_ID
    JOIN USERS U2 ON T.DRIVER_ID = U2.USERS_ID
    WHERE U1.BANNED = 'No'
      AND U2.BANNED = 'No'
      AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
    GROUP BY T.REQUEST_AT
)
SELECT 
    C_TOTAL.DAY AS Day,
    ROUND(
        IFNULL(C_CANCEL.CANCELLED,0) /
        IFNULL(C_TOTAL.TOTAL_TRIPS,0), 2)
        AS 'Cancellation Rate'
FROM COUNT_OF_TOTAL C_TOTAL
LEFT JOIN COUNT_OF_CANCEL C_CANCEL ON C_TOTAL.DAY = C_CANCEL.DAY;
