# Write your MySQL query statement below
SELECT employee_id
FROM EMPLOYEES E1
WHERE E1.SALARY<30000
AND E1.MANAGER_ID IS NOT NULL
AND (
    SELECT E2.EMPLOYEE_ID
    FROM EMPLOYEES E2
    WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID
) IS NULL
ORDER BY EMPLOYEE_ID