-- METHOD 1
SELECT E1.NAME as name
from EMPLOYEE E1
JOIN EMPLOYEE E2
ON E1.ID = E2.MANAGERID
GROUP BY E2.MANAGERID
HAVING COUNT(*)>4

-- METHOD 2
-- SELECT E1.NAME AS name
-- FROM EMPLOYEE E1
-- WHERE E1.ID IN (
--     SELECT E2.MANAGERID
--     FROM EMPLOYEE E2
--     GROUP BY E2.MANAGERID
--     HAVING COUNT(*) > 4
-- )
