-- DELETE p1 FROM Person p1
-- JOIN Person p2 
-- ON p1.email = p2.email AND p1.id > p2.id;

WITH DUPLICATE_EMAIL_ID AS (
    SELECT MIN(ID) AS ID
    FROM PERSON
    GROUP BY EMAIL
)
DELETE FROM PERSON 
WHERE ID NOT IN (SELECT ID FROM DUPLICATE_EMAIL_ID);