
SELECT P.product_id ,
    IFNULL(
    ROUND(SUM(P.price * U.units) / SUM(U.units),2)
    ,0)  AS average_price
FROM PRICES P
LEFT JOIN UNITSSOLD U
ON P.PRODUCT_ID = U.PRODUCT_ID AND
U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID