SELECT sell_date,
    COUNT(DISTINCT(PRODUCT)) AS "num_sold",
    GROUP_CONCAT(
        -- U DONT NEED TO MENTION 'SELECT'
        DISTINCT PRODUCT
        ORDER BY PRODUCT
        SEPARATOR ",") AS "products"
FROM ACTIVITIES
GROUP BY SELL_DATE
ORDER BY SELL_DATE