# Write your MySQL query statement below
SELECT U.NAME,
    SUM(T.AMOUNT) AS "BALANCE"
FROM USERS U
LEFT JOIN TRANSACTIONS T
ON U.ACCOUNT = T.ACCOUNT
GROUP BY T.ACCOUNT
HAVING BALANCE>10000
ORDER BY U.name